# ==========================================
# Aegis OS: Cloud Migration Automation Script
# Generated by Antigravity AI
# ==========================================

param (
    [string]$DropletIP = $(Read-Host "Enter your new DigitalOcean Droplet Cloud IP Address")
)

$localSparky = "aewoodyard@192.168.0.176"
$privateKey = "$env:USERPROFILE\.ssh\id_proart"
$cloudDroplet = "root@$DropletIP" # DigitalOcean default user is root

Write-Host ""
Write-Host "--- AEGIS OS CLOUD MIGRATION INITIALIZING ---" -ForegroundColor Cyan
Write-Host "-------------------------------------------"

# Step 1: Verify Local SSH Key to Droplet works
Write-Host ""
Write-Host "[STEP 1] Verifying SSH key authentication to Cloud Droplet..." -ForegroundColor Yellow
$testSSH = $null | ssh -T -i $privateKey -o ConnectTimeout=5 -o StrictHostKeyChecking=no $cloudDroplet "echo SUCCESS" 2>$null
if ($testSSH -ne "SUCCESS") {
    Write-Host "[ERROR] Could not connect to your new Droplet at $DropletIP." -ForegroundColor Red
    Write-Host "        Please make sure the Droplet is active and your local SSH public key (~/.ssh/id_proart.pub) was added during creation." -ForegroundColor Red
    Exit
}
Write-Host "[SUCCESS] SSH connection to Cloud Droplet verified successfully!" -ForegroundColor Green

# Step 2: Generate SSH Key on local Sparky if missing
Write-Host ""
Write-Host "[STEP 2] Setting up SSH key pair on Sparky..." -ForegroundColor Yellow
$sparkyKeyCheck = $null | ssh -T $localSparky "test -f ~/.ssh/id_ed25519 && echo EXISTS || echo MISSING"
if ($sparkyKeyCheck -eq "MISSING") {
    Write-Host "Generating new Ed25519 SSH key on Sparky..." -ForegroundColor Gray
    $null | ssh -T $localSparky "ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519" >$null
    Write-Host "[OK] Key generated successfully on Sparky." -ForegroundColor Green
} else {
    Write-Host "[OK] Sparky SSH key already exists." -ForegroundColor Green
}

# Step 3: Fetch Sparky's public key
$sparkyPubKey = $null | ssh -T $localSparky "cat ~/.ssh/id_ed25519.pub"
if (-not $sparkyPubKey) {
    Write-Host "[ERROR] Could not retrieve Sparky SSH public key." -ForegroundColor Red
    Exit
}

# Step 4: Authorize Sparky on Cloud Droplet
Write-Host ""
Write-Host "[STEP 3] Authorizing Sparky direct connection to Cloud Droplet..." -ForegroundColor Yellow
# Use safe string concatenation to avoid nested quote parsing issues
$authCommand = 'mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo "' + $sparkyPubKey + '" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys'
$null | ssh -T -i $privateKey $cloudDroplet $authCommand
Write-Host "[OK] Sparky has been authorized to connect directly to the Cloud Droplet!" -ForegroundColor Green

# Step 5: Trigger Direct Database and Environment Copy from Sparky to Cloud Droplet
Write-Host ""
Write-Host "[STEP 4] Triggering server-to-server High Speed database scp..." -ForegroundColor Yellow
Write-Host "        (This copies the 5.03 GB database directly, bypassing your home upload bandwidth!)" -ForegroundColor Gray

# Ensure the target folders exist on droplet
$null | ssh -T -i $privateKey $cloudDroplet "mkdir -p ~/aegis-os/data"

# Copy the .env file and database files directly using scp from Sparky to Cloud Droplet
$scpEnvCmd = 'scp -o StrictHostKeyChecking=no ~/aegis-os/.env root@' + $DropletIP + ':~/aegis-os/'
$scpDbCmd = 'scp -o StrictHostKeyChecking=no ~/aegis-os/data/*.db root@' + $DropletIP + ':~/aegis-os/data/'

$null | ssh -T $localSparky $scpEnvCmd
$null | ssh -T $localSparky $scpDbCmd

Write-Host "[SUCCESS] Database and environment transfer completed successfully!" -ForegroundColor Green

# Step 6: Deploy codebase and setup dependencies on Droplet
Write-Host ""
Write-Host "[STEP 5] Deploying Aegis OS environment and dependencies on Droplet..." -ForegroundColor Yellow

# Use literal here-string (@' ... '@) to prevent PowerShell from trying to parse bash symbols
$setupCmd = @'
apt-get update && apt-get install -y python3-venv python3-pip nodejs npm sqlite3 rsync
if [ ! -d ~/aegis-os/.git ]; then
    git clone https://github.com/woodyardae/aegis.git ~/aegis-os-tmp
    cp -rp ~/aegis-os-tmp/. ~/aegis-os/
    rm -rf ~/aegis-os-tmp
else
    cd ~/aegis-os && git pull origin main
fi
cd ~/aegis-os
python3 -m venv venv
./venv/bin/pip install flask requests python-dotenv duckdb
npm install
'@

$null | ssh -T -i $privateKey $cloudDroplet $setupCmd
Write-Host "[OK] Aegis OS codebase and virtual environment initialized!" -ForegroundColor Green

# Step 7: Configure System Services on Cloud Droplet
Write-Host ""
Write-Host "[STEP 6] Configuring active system services on Cloud Droplet..." -ForegroundColor Yellow

# Use literal here-string (@' ... '@) to prevent PowerShell from trying to parse systemd configurations
$serviceSetup = @'
cp ~/aegis-os/aegis-scout.service /etc/systemd/system/
cp ~/aegis-os/aegis-brain-api.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable aegis-scout
systemctl start aegis-scout
systemctl enable aegis-brain-api
systemctl start aegis-brain-api
'@

$null | ssh -T -i $privateKey $cloudDroplet $serviceSetup
Write-Host "[OK] Cloud system daemons successfully enabled and running 24/7!" -ForegroundColor Green

Write-Host ""
Write-Host "--- AEGIS OS MIGRATION COMPLETED SUCCESSFULLY ---" -ForegroundColor Green
Write-Host "=================================================="
Write-Host "Cloud API listening on: http://$DropletIP:3000" -ForegroundColor Cyan
Write-Host "Scout is currently compiling horizons in the cloud!" -ForegroundColor Cyan
